// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudCommerceConsumerProcurementV1
import GoogleCloudWkt
import GoogleLongRunning

func sample(billingAccountId: String, orderId: String, ) async throws {
  let client = try GoogleCloudCommerceConsumerProcurementV1.LicenseManagementServiceClient()
  let response = try await client.updateLicensePool(
    request: UpdateLicensePoolRequest()
      .with {
        $0.licensePool = LicensePool().with {
          $0.name = "billingAccounts/\(billingAccountId)/orders/\(orderId)/licensePool"
        }
        $0.updateMask = GoogleCloudWkt.FieldMask(paths: ["field.path1", "field.path2"])
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      try await sample(billingAccountId: "[placeholder]", orderId: "[placeholder]", )
    } catch {
      print("Error: \(error)")
    }
  }
}
