// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Assignment protocol for a license pool.
public struct AssignmentProtocol: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of assignment protocol.
  public var assignmentType: OneOf_AssignmentType? = nil

  /// Initialize a new instance of `AssignmentProtocol`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AssignmentProtocol().with { $0.manualAssignmentType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case manualAssignmentType = "manualAssignmentType"
    case autoAssignmentType = "autoAssignmentType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var assignmentType: OneOf_AssignmentType? = nil
    let assignmentTypeCheckAndSet = {
      if assignmentType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'assignmentType'"))
      }
      assignmentType = $0
    }
    if let manualAssignmentType = try container.decodeIfPresent(
      AssignmentProtocol.ManualAssignmentType?.self, forKey: .manualAssignmentType)
    {
      try assignmentTypeCheckAndSet(.manualAssignmentType(manualAssignmentType))
    }
    if let autoAssignmentType = try container.decodeIfPresent(
      AssignmentProtocol.AutoAssignmentType?.self, forKey: .autoAssignmentType)
    {
      try assignmentTypeCheckAndSet(.autoAssignmentType(autoAssignmentType))
    }
    self.assignmentType = assignmentType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.assignmentType {
      switch choice {
      case .manualAssignmentType(let value):
        try container.encode(value, forKey: .manualAssignmentType)
      case .autoAssignmentType(let value):
        try container.encode(value, forKey: .autoAssignmentType)
      }
    }
  }

  /// Allow manual assignments triggered by administrative operations only.
  public struct ManualAssignmentType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `ManualAssignmentType`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ManualAssignmentType().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.AssignmentProtocol.ManualAssignmentType"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for automatic assignments handled by data plane operations.
  public struct AutoAssignmentType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The time to live for an inactive license. After this time has
    /// passed, the license will be automatically unassigned from the user. Must
    /// be at least 7 days, if set. If unset, the license will never expire.
    public var inactiveLicenseTtl: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `AutoAssignmentType`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AutoAssignmentType().with { $0.inactiveLicenseTtl = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.AssignmentProtocol.AutoAssignmentType"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The type of assignment protocol.
  public enum OneOf_AssignmentType: Codable, Equatable, Sendable {
    /// Allow manual assignments triggered by administrative operations only.
    indirect case manualAssignmentType(AssignmentProtocol.ManualAssignmentType?)
    /// Allow automatic assignments triggered by data plane operations.
    indirect case autoAssignmentType(AssignmentProtocol.AutoAssignmentType?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.AssignmentProtocol"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
