// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ConsumerProcurementService.CancelOrder][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.CancelOrder].
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.CancelOrder]: <doc:ConsumerProcurementService/cancelOrder(request:)>
public struct CancelOrderRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the order.
  public var name: Swift.String = Swift.String()

  /// Optional. The weak etag, which can be optionally populated, of the order
  /// that this cancel request is based on. Validation checking will only happen
  /// if the invoker supplies this field.
  public var etag: Swift.String = Swift.String()

  /// Optional. Cancellation policy of this request.
  public var cancellationPolicy: CancelOrderRequest.CancellationPolicy =
    CancelOrderRequest.CancellationPolicy()

  /// Initialize a new instance of `CancelOrderRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CancelOrderRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Indicates the cancellation policy the customer uses to cancel the order.
  public enum CancellationPolicy: Codable, Equatable, Sendable {
    /// If unspecified, cancellation will try to cancel the order, if order
    /// cannot be immediately cancelled, auto renewal will be turned off.
    /// However, caller should avoid using the value as it will yield a
    /// non-deterministic result. This is still supported mainly to maintain
    /// existing integrated usages and ensure backwards compatibility.
    case unspecified
    /// Request will cancel the whole order immediately, if order cannot be
    /// immediately cancelled, the request will fail.
    case cancelImmediately
    /// Request will cancel the auto renewal, if order is not subscription based,
    /// the request will fail.
    case cancelAtTermEnd
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cancelImmediately: return 1
      case .cancelAtTermEnd: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CANCELLATION_POLICY_UNSPECIFIED"
      case .cancelImmediately: return "CANCELLATION_POLICY_CANCEL_IMMEDIATELY"
      case .cancelAtTermEnd: return "CANCELLATION_POLICY_CANCEL_AT_TERM_END"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CancellationPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CANCELLATION_POLICY_UNSPECIFIED": self = .unspecified
      case "CANCELLATION_POLICY_CANCEL_IMMEDIATELY": self = .cancelImmediately
      case "CANCELLATION_POLICY_CANCEL_AT_TERM_END": self = .cancelAtTermEnd
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CancellationPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cancelImmediately
      case 2: self = .cancelAtTermEnd
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cancelImmediately: return try container.encode(1)
      case .cancelAtTermEnd: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.CancelOrderRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
