// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ConsumerProcurementServiceLogging: ConsumerProcurementServiceStub {
    let inner: any ConsumerProcurementServiceStub
    let logger: Logger

    public init(_ inner: any ConsumerProcurementServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-commerce-consumer-procurement-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudcommerceconsumerprocurement"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ConsumerProcurementService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func placeOrder(
      request: PlaceOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "placeOrder",
        action: {
          (r: PlaceOrderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.placeOrder(request: r, options: o)
        })
    }

    public func getOrder(
      request: GetOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOrder",
        action: {
          (r: GetOrderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.Order
          in
          return try await self.inner.getOrder(request: r, options: o)
        })
    }

    public func listOrders(
      request: ListOrdersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOrders",
        action: {
          (r: ListOrdersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse
          in
          return try await self.inner.listOrders(request: r, options: o)
        })
    }

    public func modifyOrder(
      request: ModifyOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "modifyOrder",
        action: {
          (r: ModifyOrderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.modifyOrder(request: r, options: o)
        })
    }

    public func cancelOrder(
      request: CancelOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOrder",
        action: {
          (r: CancelOrderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelOrder(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
