// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// ConsumerProcurementService allows customers to make purchases of products
/// served by the Cloud Commerce platform.
///
///
/// When purchases are made, the
/// [ConsumerProcurementService][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService]
/// programs the appropriate backends, including both Google's own
/// infrastructure, as well as third-party systems, and to enable billing setup
/// for charging for the procured item.
///
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService]: <doc:ConsumerProcurementService>
///
/// @Snippet(path: "ConsumerProcurementServiceQuickstart")
public class ConsumerProcurementServiceClient: Clients.ConsumerProcurementServiceProtocol {
  let inner: any Clients.ConsumerProcurementServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ConsumerProcurementServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConsumerProcurementServiceStub =
      try Clients.ConsumerProcurementServiceTransport(options)
    inner = Clients.ConsumerProcurementServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConsumerProcurementServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new [Order][google.cloud.commerce.consumer.procurement.v1.Order].
  ///
  /// This API only supports GCP spend-based committed use
  /// discounts specified by GCP documentation.
  ///
  /// The returned long-running operation is in-progress until the backend
  /// completes the creation of the resource. Once completed, the order is
  /// in
  /// [OrderState.ORDER_STATE_ACTIVE][google.cloud.commerce.consumer.procurement.v1.OrderState.ORDER_STATE_ACTIVE].
  /// In case of failure, the order resource will be removed.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_PlaceOrder")
  public func placeOrder(
    request: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.placeOrder(request: request, options: options)
  }

  /// Creates a new [Order][google.cloud.commerce.consumer.procurement.v1.Order].
  ///
  /// This API only supports GCP spend-based committed use
  /// discounts specified by GCP documentation.
  ///
  /// The returned long-running operation is in-progress until the backend
  /// completes the creation of the resource. Once completed, the order is
  /// in
  /// [OrderState.ORDER_STATE_ACTIVE][google.cloud.commerce.consumer.procurement.v1.OrderState.ORDER_STATE_ACTIVE].
  /// In case of failure, the order resource will be removed.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_PlaceOrder")
  public func placeOrder(
    withPolling: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Order>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Order(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.placeOrder(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Returns the requested
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_GetOrder")
  public func getOrder(
    request: GetOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    try await self.inner.getOrder(request: request, options: options)
  }

  /// Lists [Order][google.cloud.commerce.consumer.procurement.v1.Order]
  /// resources that the user has access to, within the scope of the parent
  /// resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ListOrders")
  public func listOrders(
    request: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse {
    try await self.inner.listOrders(request: request, options: options)
  }

  /// Lists [Order][google.cloud.commerce.consumer.procurement.v1.Order]
  /// resources that the user has access to, within the scope of the parent
  /// resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ListOrders")
  public func listOrders(
    byItem: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Order, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOrders(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Modifies an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ModifyOrder")
  public func modifyOrder(
    request: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.modifyOrder(request: request, options: options)
  }

  /// Modifies an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ModifyOrder")
  public func modifyOrder(
    withPolling: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Order>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Order(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.modifyOrder(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Cancels an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order]. Every product
  /// procured in the Order will be cancelled.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_CancelOrder")
  public func cancelOrder(
    request: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.cancelOrder(request: request, options: options)
  }

  /// Cancels an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order]. Every product
  /// procured in the Order will be cancelled.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_CancelOrder")
  public func cancelOrder(
    withPolling: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Order>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Order(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.cancelOrder(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ConsumerProcurementService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConsumerProcurementServiceClient`.
  ///
  /// To mock `ConsumerProcurementServiceClient` change your functions to receive
  /// `some ConsumerProcurementServiceProtocol` or `any ConsumerProcurementServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConsumerProcurementServiceProtocol {
    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrder(request: PlaceOrderRequest) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrder(withPolling: PlaceOrderRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Order>

    /// See `ConsumerProcurementServiceClient.getOrder`.
    func getOrder(request: GetOrderRequest) async throws
      -> GoogleCloudCommerceConsumerProcurementV1.Order

    /// See `ConsumerProcurementServiceClient.getOrder`.
    func getOrder(
      name: Swift.String,
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(request: ListOrdersRequest) async throws
      -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(
      byItem: ListOrdersRequest
    ) throws -> any AsyncSequence<Order, Swift.Error>

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Order, Swift.Error>

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrder(request: ModifyOrderRequest) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrder(withPolling: ModifyOrderRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Order>

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrder(request: CancelOrderRequest) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrder(withPolling: CancelOrderRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Order>

    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrder(
      request: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrder(
      withPolling: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Order>

    /// See `ConsumerProcurementServiceClient.getOrder`.
    func getOrder(
      request: GetOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(
      request: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(
      byItem: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Order, Swift.Error>

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrder(
      request: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrder(
      withPolling: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Order>

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrder(
      request: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrder(
      withPolling: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Order>
  }
}

// Default implementations
extension Clients.ConsumerProcurementServiceProtocol {
  public func placeOrder(request: PlaceOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.placeOrder(request: request, options: .init())
  }

  public func placeOrder(
    request: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func placeOrder(withPolling: PlaceOrderRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Order>
  {
    try await self.placeOrder(withPolling: withPolling, options: .init())
  }

  public func placeOrder(
    withPolling: PlaceOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getOrder(request: GetOrderRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.Order
  {
    try await self.getOrder(request: request, options: .init())
  }

  public func getOrder(
    request: GetOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOrder(
    name: Swift.String,
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    let request = GetOrderRequest().with {
      $0.name = name
    }
    return try await self.getOrder(request: request)
  }

  public func listOrders(request: ListOrdersRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse
  {
    try await self.listOrders(request: request, options: .init())
  }

  public func listOrders(
    request: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOrders(
    byItem: ListOrdersRequest
  ) throws -> any AsyncSequence<Order, Swift.Error> {
    try self.listOrders(byItem: byItem, options: .init())
  }

  public func listOrders(
    byItem: ListOrdersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Order, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrders(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Order, Swift.Error> {
    let request = ListOrdersRequest().with {
      $0.parent = parent
    }
    return try self.listOrders(byItem: request)
  }

  public func modifyOrder(request: ModifyOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.modifyOrder(request: request, options: .init())
  }

  public func modifyOrder(
    request: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func modifyOrder(withPolling: ModifyOrderRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Order>
  {
    try await self.modifyOrder(withPolling: withPolling, options: .init())
  }

  public func modifyOrder(
    withPolling: ModifyOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func cancelOrder(request: CancelOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.cancelOrder(request: request, options: .init())
  }

  public func cancelOrder(
    request: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOrder(withPolling: CancelOrderRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Order>
  {
    try await self.cancelOrder(withPolling: withPolling, options: .init())
  }

  public func cancelOrder(
    withPolling: CancelOrderRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Order> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Order>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
