// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

extension Clients {
  final class LicenseManagementServiceRetry: LicenseManagementServiceStub {
    let inner: any LicenseManagementServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any LicenseManagementServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getLicensePool(
      request: GetLicensePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLicensePoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.LicensePool
          in
          return try await self.inner.getLicensePool(request: r, options: o)
        })
    }

    public func updateLicensePool(
      request: UpdateLicensePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateLicensePoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.LicensePool
          in
          return try await self.inner.updateLicensePool(request: r, options: o)
        })
    }

    public func assign(
      request: AssignRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AssignRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse
          in
          return try await self.inner.assign(request: r, options: o)
        })
    }

    public func unassign(
      request: UnassignRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UnassignRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse
          in
          return try await self.inner.unassign(request: r, options: o)
        })
    }

    public func enumerateLicensedUsers(
      request: EnumerateLicensedUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: EnumerateLicensedUsersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse
          in
          return try await self.inner.enumerateLicensedUsers(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
