// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A single item within an order.
public struct LineItem: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Line item ID.
  public var lineItemId: Swift.String = Swift.String()

  /// Output only. Current state and information of this item. It tells what,
  /// e.g. which offer, is currently effective.
  public var lineItemInfo: LineItemInfo? = nil

  /// Output only. A change made on the item which is pending and not yet
  /// effective. Absence of this field indicates the line item is not undergoing
  /// a change.
  public var pendingChange: LineItemChange? = nil

  /// Output only. Changes made on the item that are not pending anymore which
  /// might be because they already took effect, were reverted by the customer,
  /// or were rejected by the partner. No more operations are allowed on these
  /// changes.
  public var changeHistory: [LineItemChange] = []

  /// Initialize a new instance of `LineItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineItem().with { $0.lineItemId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LineItem"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
