// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A change made on a line item.
public struct LineItemChange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Change ID.
  /// All changes made within one order update operation have the same change_id.
  public var changeId: Swift.String = Swift.String()

  /// Required. Type of the change to make.
  public var changeType: LineItemChangeType = LineItemChangeType()

  /// Output only. Line item info before the change.
  public var oldLineItemInfo: LineItemInfo? = nil

  /// Line item info after the change.
  public var newLineItemInfo: LineItemInfo? = nil

  /// Output only. State of the change.
  public var changeState: LineItemChangeState = LineItemChangeState()

  /// Output only. Provider-supplied message explaining the LineItemChange's
  /// state. Mainly used to communicate progress and ETA for provisioning in the
  /// case of `PENDING_APPROVAL`, and to explain why the change request was
  /// denied or canceled in the case of `REJECTED` and `CANCELED` states.
  public var stateReason: Swift.String = Swift.String()

  /// Output only. Predefined enum types for why this line item change is in
  /// current state. For example, a line item change's state could be
  /// `LINE_ITEM_CHANGE_STATE_COMPLETED` because of end-of-term expiration,
  /// immediate cancellation initiated by the user, or system-initiated
  /// cancellation.
  public var changeStateReasonType: LineItemChangeStateReasonType = LineItemChangeStateReasonType()

  /// Output only. A time at which the change became or will become (in case of
  /// pending change) effective.
  public var changeEffectiveTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when change was initiated.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when change was updated, e.g. approved/rejected by
  /// partners or cancelled by the user.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `LineItemChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineItemChange().with { $0.changeId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LineItemChange"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
