// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ConsumerProcurementService.ListOrders][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.ListOrders].
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.ListOrders]: <doc:ConsumerProcurementService/listOrders(request:)>
public struct ListOrdersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource to query for orders.
  /// This field has the form `billingAccounts/{billing-account-id}`.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of entries requested.
  /// The default page size is 25 and the maximum page size is 200.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The token for fetching the next page.
  public var pageToken: Swift.String = Swift.String()

  /// Filter that you can use to limit the list request.
  ///
  /// A query string that can match a selected set of attributes
  /// with string values. For example, `display_name=abc`.
  /// Supported query attributes are
  ///
  /// * `display_name`
  ///
  ///
  /// If the query contains special characters other than letters,
  /// underscore, or digits, the phrase must be quoted with double quotes. For
  /// example, `display_name="foo:bar"`, where the display name needs to be
  /// quoted because it contains special character colon.
  ///
  /// Queries can be combined with `OR`, and `NOT` to form more complex queries.
  /// You can also group them to force a desired evaluation order.
  /// For example, `display_name=abc OR display_name=def`.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListOrdersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOrdersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.ListOrdersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
