// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ConsumerProcurementService.ModifyOrder][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.ModifyOrder].
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.ModifyOrder]: <doc:ConsumerProcurementService/modifyOrder(request:)>
public struct ModifyOrderRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the order to update.
  public var name: Swift.String = Swift.String()

  /// Optional. Modifications for an existing Order created by an Offer.
  /// Required when Offer based Order is being modified, except for when going
  /// from an offer to a public plan.
  public var modifications: [ModifyOrderRequest.Modification] = []

  /// Optional. Updated display name of the order, leave as empty if you do not
  /// want to update current display name.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The weak etag, which can be optionally populated, of the order
  /// that this modify request is based on. Validation checking will only happen
  /// if the invoker supplies this field.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `ModifyOrderRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ModifyOrderRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Modifications to make on the order.
  public struct Modification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. ID of the existing line item to make change to.
    /// Required when change type is
    /// [LineItemChangeType.LINE_ITEM_CHANGE_TYPE_UPDATE] or
    /// [LineItemChangeType.LINE_ITEM_CHANGE_TYPE_CANCEL].
    public var lineItemId: Swift.String = Swift.String()

    /// Required. Type of change to make.
    public var changeType: LineItemChangeType = LineItemChangeType()

    /// Optional. The line item to update to.
    /// Required when change_type is
    /// [LineItemChangeType.LINE_ITEM_CHANGE_TYPE_CREATE] or
    /// [LineItemChangeType.LINE_ITEM_CHANGE_TYPE_UPDATE].
    public var newLineItemInfo: LineItemInfo? = nil

    /// Optional. Auto renewal behavior of the subscription for the update.
    /// Applied when change_type is
    /// [LineItemChangeType.LINE_ITEM_CHANGE_TYPE_UPDATE]. Follows plan default
    /// config when this field is not specified.
    public var autoRenewalBehavior: AutoRenewalBehavior = AutoRenewalBehavior()

    /// Initialize a new instance of `Modification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Modification().with { $0.lineItemId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.ModifyOrderRequest.Modification"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.ModifyOrderRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
