// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// User-provided Parameters.
public struct Parameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the parameter.
  public var name: Swift.String = Swift.String()

  /// Value of parameter.
  public var value: Parameter.Value? = nil

  /// Initialize a new instance of `Parameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Parameter().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public struct Value: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The kind of value.
    public var kind: OneOf_Kind? = nil

    /// Initialize a new instance of `Value`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Value().with { $0.int64Value = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case int64Value = "int64Value"
      case stringValue = "stringValue"
      case doubleValue = "doubleValue"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let int64Value = try container.decodeIfPresent(Swift.Int64.self, forKey: .int64Value) {
        try kindCheckAndSet(.int64Value(int64Value))
      }
      if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
        try kindCheckAndSet(.stringValue(stringValue))
      }
      if let doubleValue = try container.decodeIfPresent(Swift.Double.self, forKey: .doubleValue) {
        try kindCheckAndSet(.doubleValue(doubleValue))
      }
      self.kind = kind
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .int64Value(let value):
          try container.encode(value, forKey: .int64Value)
        case .stringValue(let value):
          try container.encode(value, forKey: .stringValue)
        case .doubleValue(let value):
          try container.encode(value, forKey: .doubleValue)
        }
      }
    }

    /// The kind of value.
    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// Represents an int64 value.
      case int64Value(Swift.Int64)
      /// Represents a string value.
      case stringValue(Swift.String)
      /// Represents a double value.
      case doubleValue(Swift.Double)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter.Value"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
