// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ConsumerProcurementService.PlaceOrder][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.PlaceOrder].
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.PlaceOrder]: <doc:ConsumerProcurementService/placeOrder(request:)>
public struct PlaceOrderRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent resource.
  /// This field has the form  `billingAccounts/{billing-account-id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The user-specified name of the order being placed.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Places order for offer. Required when an offer-based order is
  /// being placed.
  public var lineItemInfo: [LineItemInfo] = []

  /// Optional. A unique identifier for this request.
  /// The server will ignore subsequent requests that provide a duplicate request
  /// ID for at least 24 hours after the first request.
  ///
  /// The request ID must be a valid
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `PlaceOrderRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PlaceOrderRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.PlaceOrderRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
