// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Subscription information.
public struct Subscription: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The timestamp when the subscription begins, if applicable.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The timestamp when the subscription ends, if applicable.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Whether auto renewal is enabled by user choice on current subscription.
  /// This field indicates order/subscription status after pending plan change is
  /// cancelled or rejected.
  public var autoRenewalEnabled: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Subscription`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Subscription().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Subscription"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
